# See https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
sudo: required
dist: trusty

# Only run travis on the master branch (and PRs), not all branches
branches:
  only:
    - master

language: python

addons:
  firefox: latest
  chrome: stable

python:
  - "2.7"

# cache pip and npm package installations
cache:
  pip: true
  directories:
    - node_modules

# limit the depth of the commits we clone
git:
  depth: 5

env:
  global:
    - ISSUES_REPO_URI=webcompat/webcompat-tests/issues

notifications:
  webhooks: https://www.travisbuddy.com/?insertMode=update
  on_success: never

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - travis_retry npm install
  - travis_retry npm run pip
  - travis_retry npm run config
  - which firefox
  - java -version
  - firefox --version

before_script:
  - sleep 5
  # lint JS in default eslint task
  - npm run lint
  - npm run build
  # lint python
  - pep8 --ignore=E402 webcompat/ tests/ config/secrets.py.example

# now run the tests!
script:
  - nosetests
  - python run.py -t &
  - sleep 5
  - npm run test:js -- --reporters="runner" --firefoxBinary=`which firefox`
